export const ON_LOGIN_REQUESTED = 'ON_LOGIN_REQUESTED';
export const ON_LOGIN_COMPLETED = 'ON_LOGIN_COMPLETED';
export const ON_SCHOOL_LOGIN_COMPLETED = 'ON_SCHOOL_LOGIN_COMPLETED';
export const ON_SCHOOL_LOGIN_FAILED = 'ON_SCHOOL_LOGIN_FAILED';
export const ON_LOGOUT_REQUESTED = 'ON_LOGOUT_REQUESTED';
export const ON_LOGOUT_COMPLETED = 'ON_LOGOUT_COMPLETED';
