export const ON_AUTHORISATION_REQUESTED = 'ON_AUTHORISATION_REQUESTED';
export const ON_AUTHORISATION_COMPLETED = 'ON_AUTHORISATION_COMPLETED';
export const ON_AUTHORISATION_FAILED = 'ON_AUTHORISATION_FAILED';
