export const ON_SIGNUP_REQUESTED = 'ON_SIGNUP_REQUESTED';
export const ON_SIGNUP_COMPLETED = 'ON_SIGNUP_COMPLETED';
export const ON_SIGNUP_FAILED = 'ON_SIGNUP_FAILED';
export const ON_UPDATE_USER_REQUESTED = 'ON_UPDATE_USER_REQUESTED';
export const ON_UPDATE_USER_COMPLETED = 'ON_UPDATE_USER_COMPLETED';
export const ON_UPDATE_USER_FAILED = 'ON_UPDATE_USER_FAILED';
