export const ON_EMAIL_SUBMITTING = 'ON_EMAIL_SUBMITTING';
export const ON_EMAIL_SUBMITTED = 'ON_EMAIL_SUBMITTED';
export const ON_PAYMENT_REQUESTED = 'ON_PAYMENT_REQUESTED';
export const ON_PAYMENT_COMPLETED = 'ON_PAYMENT_COMPLETED';
