export const ON_SCHOOL_NAMES_REQUESTED = 'ON_SCHOOL_NAMES_REQUESTED';
export const ON_SCHOOL_NAMES_FETCHED = 'ON_SCHOOL_NAMES_FETCHED';
export const ON_SCHOOL_DATA_REQUESTED = 'ON_SCHOOL_DATA_REQUESTED';
export const ON_SCHOOL_DATA_FETCHED = 'ON_SCHOOL_DATA_FETCHED';
